---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: booleanproperties.domotik8s.io
spec:
  group: domotik8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:

            # SPEC
            spec:
              type: object
              properties:

                # ADDRESS
                address:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    system: 
                      type: string
                    instance: 
                      type: string

                # STATE
                state:
                  type: object
                  properties:
                    value:
                      type: boolean

                # SEMANTIC
                semantic:
                  type: object
                  properties:
                    meaning:
                      type: string
                      enum:
                        - "OFF_ON"
                        - "FALSE_TRUE"
                        - "DISABLE_ENABLE"
                        - "NORAMP_RAMP"
                        - "NOALARM_ALARM"
                        - "LOW_HIGH"
                        - "DECREASE_INCREASE"
                        - "UP_DOWN"
                        - "OPEN_CLOSE"
                        - "STOP_START"
                        - "INACTIVE_ACTIVE"
                        - "NOTINVERTED_INVERTED"
                        - "STARSTOP_CYCLICALLY"
                        - "FIXED_CALCULATED"
                        - "DUMMY_TRIGGER"
                        - "TRIGGER_TRIGGER"
                        - "CLOSED_OPEN"
                        - "OR_AND"
                        - "SCENEA_SCENEB"
                        - "UPDOWN_UPDOWNSTEPSTOP"
                        - "COOLING_HEATING"
                    reversed:
                      type: boolean
                      default: false

                # ACCESS
                access: 
                  type: array
                  items:
                    type: string
                    enum:
                      - READ
                      - WRITE

                # LOCK
                locked:
                  type: boolean

            # STATUS
            status:
              type: object
              properties:

                # STATE
                state:
                  type: object
                  properties:
                    value:
                      type: boolean

                # LASTUPDATED
                lastUpdated:
                    type: string
                    format: date-time
  scope: Namespaced
  names:
    plural: booleanproperties
    singular: booleanproperty
    kind: BooleanProperty
    shortNames:
      - bp
      - bps
