---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devices.domotik8s.io
spec:
  group: domotik8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object

          properties:

            # SPEC
            spec:
              type: object
              properties:

                # PROPERTIES
                properties:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      name:
                        type: string
                      system:
                        type: string
                      instance:
                        type: string
                    x-kubernetes-preserve-unknown-fields: true
                  # This line allows for fields other than those explicitly defined above
                  x-kubernetes-preserve-unknown-fields: true

                # STATE
                state:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

            # STATUS
            status:
              type: object
              properties:

                # STATE
                state:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

                # LASTUPDATED
                lastUpdated:
                    type: string
                    format: date-time

  scope: Cluster
  names:
    plural: devices
    singular: device
    kind: Device
    shortNames:
      - dev
      - devs
