---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.domotik8s.io
spec:
  group: domotik8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:


            # SPEC
            spec:
              type: object
              properties:

                # SELECTOR
                selector:
                  type: object
                  properties:

                    # shared
                    type:
                      type: string
                      enum: ["LabelSelector", "ValueSelector", "CompositeSelector"]

                    # label
                    name:
                      type: string
                    labelValue:
                      type: string
                    comparator:
                      type: string
                      enum: [ "Equals", "Contains" ]
                    ignoreCase:
                      type: boolean

                    # value
                    value:
                      type: string

                    # composite
                    logic:
                        type: string
                        enum: [ "And", "Or" ]
                    children:
                      type: array
                      items:
                        type: object
                        properties:

                          # shared
                          type:
                            type: string
                            enum: ["LabelSelector", "ValueSelector", "CompositeSelector"]

                          # label
                          name:
                            type: string
                          labelValue:
                            type: string
                          comparator:
                            type: string
                            enum: [ "Equals", "Contains" ]
                          ignoreCase:
                            type: boolean

                          # value
                          value:
                            type: string

                          # composite
                          logic:
                            type: string
                            enum: [ "And", "Or" ]
                          children:
                            type: array
                            items:
                              type: object
                              properties:

                                # shared
                                type:
                                  type: string
                                  enum: ["LabelSelector", "ValueSelector", "CompositeSelector"]

                                # label
                                name:
                                  type: string
                                labelValue:
                                  type: string
                                comparator:
                                  type: string
                                  enum: [ "Equals", "Contains" ]
                                ignoreCase:
                                  type: boolean

                                # value
                                value:
                                  type: string


                # AGGREGATION
                aggregation:
                  type: object
                  properties:
                    method:
                      type: string
                      enum: ["Min", "Max", "Sum", "ArithmeticMean"]

            # STATUS
            status:
              type: object
              properties:

                # MEMBERS
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      namespace:
                        type: string
                      name:
                        type: string

                # RESULT
                result:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    value:
                      x-kubernetes-preserve-unknown-fields: true

                # LASTUPDATED
                lastUpdated:
                    type: string
                    format: date-time

  scope: Namespaced
  names:
    plural: groups
    singular: group
    kind: Group
    shortNames:
      - grp
      - gp