---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: groups.domotik8s.io
spec:
  group: domotik8s.io
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:


            # SPEC
            spec:
              type: object
              properties:

                # SELECTOR
                selector:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: ["LabelSelector", "ValueSelector", "CompositeSelector"]
                    name:
                      type: string
                    value:
                      type: string
                    logic:
                        type: string
                        enum: [ "And", "Or" ]
                    children:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            enum: ["LabelSelector", "ValueSelector"]
                          name:
                            type: string
                          value:
                            type: string

            # STATUS
            status:
              type: object
              properties:
                # MEMBERGS
                members:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      namespace:
                        type: string
                      name:
                        type: string

                # LASTUPDATED
                lastUpdated:
                    type: string
                    format: date-time

  scope: Namespaced
  names:
    plural: groups
    singular: group
    kind: Group
    shortNames:
      - grp
      - gp