server:
  port: 8082

logging:
  level:
    root: INFO
    "[io.kubernetes]": TRACE
    "[org.springframework]": DEBUG
    "[io.domotik8s]": DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true